# Generated by Django 4.1.5 on 2023-01-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('dirigeant', models.CharField(max_length=100)),
                ('CA', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion'), ('MAUVAIS ETAT', 'Mauvais Etat'), ('INUTILISABLE', 'Inutilisable')], default='NEUF', max_length=15)),
                ('statut', models.CharField(choices=[('LIBRE', 'Libre'), ('VENDU', 'Vendu')], default='UND', max_length=10)),
                ('lieu_stockage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meubles.magasin')),
            ],
        ),
    ]
